<?php

return [
    'limitPaginate' => 20,
    'limitData' => 15,
    'limitDataRelated' => 10,
    'selectProduct' => [
        'id',
        'store_id',
        'name',
        'description',
        'price',
        'discount',
        'qty_in_stock',
        'point_value',
        'allow_call',
        'allow_add_cart',
        'thumbnail',
        'type',
        'product_type'
    ],
    'selectStore' => [
        'id',
        'user_id',
        'name',
        'address',
        'description',
        'phone',
        'patent_number',
        'logo',
        'cover_image',
        'map',
        'qr_code',
        'type',
        'province_id',
        'district_id',
        'commune_id',
        'village_id'
    ],
    'selectBrand' => [
        'brands.id',
        'brands.parent_id',
        'brands.name',
        'brands.image',
        'brands.status',
        'brands.ordering',
    ],
    'selectCategory' => [
        'id',
        'parent_id',
        'name',
        'image',
        'type',
        'ordering',
    ],
    'selectJob' => [
        'id',
        'user_id',
        'store_id',
        'title',
        'category_id',
        'location_id',
        'view',
        'image',
        'year_experience',
        'is_negotiate',
        'salary_from',
        'salary_to',
        'job_type',
        'status',
        'description'
    ],
    'selectService' => [
        'id',
        'name',
        'price',
        'description',
        'discount',
        'qty_in_stock',
        'point_value',
        'image',
        'status',
        'user_id',
        'garage_id'
    ],
    'selectNotification' => [
        'id',
        'booking_id',
        'member_id',
        'garage_id',
        'title',
        'description',
        'type',
        'is_read_member',
        'is_read_garage',
        'status',
        'created_at'
    ]
];
